language: python
python:
  - "3.6"
  - "3.7"
# command to install dependencies
install:
  - pip3 install cordial
  - pip3 install -r requirements.txt

script:
  - python3 -m unittest discover cordial/tests "all_tests.py"